import { Theme } from '../types';

export const themes: Record<string, Theme> = {
  dark: {
    colors: {
      textColor: '#f5f5f5',
      headerFooterBg: '#2c2c2c',
      background: '#1a1a1a',
      primaryColor: '#646cff',
      searchBackground: '#2c2c2c',
      searchColor: '#f5f5f5',
      searchBorderColor: '#444444',
      searchFocusBorderColor: '#646cff',
      placeholderColor: '#888888',
    },
    fonts: { fontFamily: "'Geist', 'Inter', sans-serif" },
    borderRadius: 20,
    height: '60dvh',
  },
  light: {
    colors: {
      textColor: '#1a1a1a',
      headerFooterBg: '#f5f5f5',
      background: '#ffffff',
      primaryColor: '#007bff',
      searchBackground: '#eaeaea',
      searchColor: '#333',
      searchBorderColor: '#cccccc',
      searchFocusBorderColor: '#007bff',
      placeholderColor: '#777777',
    },
    fonts: { fontFamily: "'Geist', 'Inter', sans-serif" },
    borderRadius: 12,
    height: '60dvh',
  },
  blue: {
    colors: {
      textColor: '#e0f7fa',
      headerFooterBg: '#01579b',
      background: '#0288d1',
      primaryColor: '#03a9f4',
      searchBackground: '#0277bd',
      searchColor: '#e0f7fa',
      searchBorderColor: '#81d4fa',
      searchFocusBorderColor: '#03a9f4',
      placeholderColor: '#b0bec5',
    },
    fonts: { fontFamily: "'Geist', 'Inter', sans-serif" },
    borderRadius: 16,
    height: '60dvh',
  },
  gradient: {
    colors: {
      textColor: '#ffffff',
      headerFooterBg: 'linear-gradient(45deg, #ff416c, #ff4b2b)',
      background: 'linear-gradient(45deg, #1e3c72, #2a5298)',
      primaryColor: '#ff416c',
      searchBackground: 'rgba(255, 255, 255, 0.2)',
      searchColor: '#ffffff',
      searchBorderColor: 'rgba(255, 255, 255, 0.5)',
      searchFocusBorderColor: '#ff4b2b',
      placeholderColor: '#dddddd',
    },
    fonts: { fontFamily: "'Geist', 'Inter', sans-serif" },
    borderRadius: 25,
    height: '60dvh',
  },
  sunset: {
    colors: {
      textColor: '#f5f5f5',
      headerFooterBg: '#2d1b2e',
      background: 'linear-gradient(135deg, #1a1025 0%, #471e3c 100%)',
      primaryColor: '#ff6b6b',
      searchBackground: '#2d1b2e',
      searchColor: '#f5f5f5',
      searchBorderColor: '#3d2b3e',
      searchFocusBorderColor: '#ff6b6b',
      placeholderColor: '#aa647b',
    },
    fonts: { fontFamily: "'Geist', 'Inter', sans-serif" },
    borderRadius: 20,
    height: '60dvh',
  },
  ocean: {
    colors: {
      textColor: '#f0f8ff',
      headerFooterBg: '#0a2342',
      background: 'linear-gradient(135deg, #0a2342 0%, #126e82 100%)',
      primaryColor: '#38b2ac',
      searchBackground: '#0a2342',
      searchColor: '#f0f8ff',
      searchBorderColor: '#0a3060',
      searchFocusBorderColor: '#38b2ac',
      placeholderColor: '#87ceeb',
    },
    fonts: { fontFamily: "'Geist', 'Inter', sans-serif" },
    borderRadius: 20,
    height: '60dvh',
  },
  monochrome: {
    colors: {
      textColor: '#f5f5f5',
      headerFooterBg: '#222222',
      background: '#111111',
      primaryColor: '#ffffff',
      searchBackground: '#222222',
      searchColor: '#f5f5f5',
      searchBorderColor: '#333333',
      searchFocusBorderColor: '#ffffff',
      placeholderColor: '#999999',
    },
    fonts: { fontFamily: "'Geist', 'Inter', sans-serif" },
    borderRadius: 12,
    height: '60dvh',
  },
  emerald: {
    colors: {
      textColor: '#e8f5e9',
      headerFooterBg: '#1a2e1a',
      background: 'linear-gradient(160deg, #0d1f0d 0%, #1b3a2a 100%)',
      primaryColor: '#4caf50',
      searchBackground: '#1a2e1a',
      searchColor: '#e8f5e9',
      searchBorderColor: '#2e5a3e',
      searchFocusBorderColor: '#66bb6a',
      placeholderColor: '#6b9b7a',
    },
    fonts: { fontFamily: "'DM Sans', sans-serif" },
    borderRadius: 16,
    height: '60dvh',
  },
  lavender: {
    colors: {
      textColor: '#f3e8ff',
      headerFooterBg: '#2d1f4e',
      background: 'linear-gradient(145deg, #1a1035 0%, #2d1b69 50%, #1a1035 100%)',
      primaryColor: '#b388ff',
      searchBackground: '#2d1f4e',
      searchColor: '#f3e8ff',
      searchBorderColor: '#4a3570',
      searchFocusBorderColor: '#b388ff',
      placeholderColor: '#9575cd',
    },
    fonts: { fontFamily: "'Plus Jakarta Sans', sans-serif" },
    borderRadius: 18,
    height: '60dvh',
  },
  ember: {
    colors: {
      textColor: '#fff3e0',
      headerFooterBg: '#2c1e10',
      background: 'linear-gradient(135deg, #1a1008 0%, #3e2215 100%)',
      primaryColor: '#ffab40',
      searchBackground: '#2c1e10',
      searchColor: '#fff3e0',
      searchBorderColor: '#5a3a20',
      searchFocusBorderColor: '#ffab40',
      placeholderColor: '#a0785a',
    },
    fonts: { fontFamily: "'Outfit', sans-serif" },
    borderRadius: 14,
    height: '60dvh',
  },
  frost: {
    colors: {
      textColor: '#e3f2fd',
      headerFooterBg: '#102a43',
      background: 'linear-gradient(150deg, #0b1929 0%, #1a3a5c 50%, #0d2137 100%)',
      primaryColor: '#40c4ff',
      searchBackground: '#102a43',
      searchColor: '#e3f2fd',
      searchBorderColor: '#1e4976',
      searchFocusBorderColor: '#40c4ff',
      placeholderColor: '#5c8ab5',
    },
    fonts: { fontFamily: "'Sora', sans-serif" },
    borderRadius: 22,
    height: '60dvh',
  },
  carbon: {
    colors: {
      textColor: '#e0e0e0',
      headerFooterBg: '#212121',
      background: '#181818',
      primaryColor: '#00e676',
      searchBackground: '#252525',
      searchColor: '#e0e0e0',
      searchBorderColor: '#383838',
      searchFocusBorderColor: '#00e676',
      placeholderColor: '#757575',
    },
    fonts: { fontFamily: "'Roboto', sans-serif" },
    borderRadius: 10,
    height: '60dvh',
  },
  candy: {
    colors: {
      textColor: '#4a1942',
      headerFooterBg: '#fce4ec',
      background: 'linear-gradient(135deg, #fff0f5 0%, #fce4ec 50%, #f3e5f5 100%)',
      primaryColor: '#e91e63',
      searchBackground: '#fff0f5',
      searchColor: '#4a1942',
      searchBorderColor: '#f8bbd0',
      searchFocusBorderColor: '#e91e63',
      placeholderColor: '#c48b9f',
    },
    fonts: { fontFamily: "'Nunito', sans-serif" },
    borderRadius: 24,
    height: '60dvh',
  },
};

export type ThemeKeys = keyof typeof themes;
