import { Theme } from '../types';

export const themes: Record<string, Theme> = {
  dark: {
    colors: {
      textColor: '#f5f5f5',
      headerFooterBg: '#2c2c2c',
      background: '#1a1a1a',
      primaryColor: '#646cff',
      searchBackground: '#2c2c2c',
      searchColor: '#f5f5f5',
      searchBorderColor: '#444444',
      searchFocusBorderColor: '#646cff',
      placeholderColor: '#888888',
    },
    fonts: { fontFamily: "'Inter', sans-serif" },
    borderRadius: 20,
    height: '60dvh',
  },
  light: {
    colors: {
      textColor: '#1a1a1a',
      headerFooterBg: '#f5f5f5',
      background: '#ffffff',
      primaryColor: '#007bff',
      searchBackground: '#eaeaea',
      searchColor: '#333',
      searchBorderColor: '#cccccc',
      searchFocusBorderColor: '#007bff',
      placeholderColor: '#777777',
    },
    fonts: { fontFamily: "'Inter', sans-serif" },
    borderRadius: 12,
    height: '60dvh',
  },
  blue: {
    colors: {
      textColor: '#e0f7fa',
      headerFooterBg: '#01579b',
      background: '#0288d1',
      primaryColor: '#03a9f4',
      searchBackground: '#0277bd',
      searchColor: '#e0f7fa',
      searchBorderColor: '#81d4fa',
      searchFocusBorderColor: '#03a9f4',
      placeholderColor: '#b0bec5',
    },
    fonts: { fontFamily: "'Inter', sans-serif" },
    borderRadius: 16,
    height: '60dvh',
  },
  gradient: {
    colors: {
      textColor: '#ffffff',
      headerFooterBg: 'linear-gradient(45deg, #ff416c, #ff4b2b)',
      background: 'linear-gradient(45deg, #1e3c72, #2a5298)',
      primaryColor: '#ff416c',
      searchBackground: 'rgba(255, 255, 255, 0.2)',
      searchColor: '#ffffff',
      searchBorderColor: 'rgba(255, 255, 255, 0.5)',
      searchFocusBorderColor: '#ff4b2b',
      placeholderColor: '#dddddd',
    },
    fonts: { fontFamily: "'Inter', sans-serif" },
    borderRadius: 25,
    height: '60dvh',
  },
  sunset: {
    colors: {
      textColor: '#f5f5f5',
      headerFooterBg: '#2d1b2e',
      background: 'linear-gradient(135deg, #1a1025 0%, #471e3c 100%)',
      primaryColor: '#ff6b6b',
      searchBackground: '#2d1b2e',
      searchColor: '#f5f5f5',
      searchBorderColor: '#3d2b3e',
      searchFocusBorderColor: '#ff6b6b',
      placeholderColor: '#aa647b',
    },
    fonts: { fontFamily: "'Inter', sans-serif" },
    borderRadius: 20,
    height: '60dvh',
  },
  ocean: {
    colors: {
      textColor: '#f0f8ff',
      headerFooterBg: '#0a2342',
      background: 'linear-gradient(135deg, #0a2342 0%, #126e82 100%)',
      primaryColor: '#38b2ac',
      searchBackground: '#0a2342',
      searchColor: '#f0f8ff',
      searchBorderColor: '#0a3060',
      searchFocusBorderColor: '#38b2ac',
      placeholderColor: '#87ceeb',
    },
    fonts: { fontFamily: "'Inter', sans-serif" },
    borderRadius: 20,
    height: '60dvh',
  },
  monochrome: {
    colors: {
      textColor: '#f5f5f5',
      headerFooterBg: '#222222',
      background: '#111111',
      primaryColor: '#ffffff',
      searchBackground: '#222222',
      searchColor: '#f5f5f5',
      searchBorderColor: '#333333',
      searchFocusBorderColor: '#ffffff',
      placeholderColor: '#999999',
    },
    fonts: { fontFamily: "'Inter', sans-serif" },
    borderRadius: 12,
    height: '60dvh',
  },
};

export type ThemeKeys = keyof typeof themes;
